# Generated by Django 4.2.4 on 2023-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exmapp', '0002_alter_exam_age_alter_exam_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
